In [ ]:
import numpy as np
import pandas as pd
# import keras
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn import neighbors
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
# from keras.callbacks import ModelCheckpoint
# from keras.models import Sequential
# from keras.layers import Dense, Activation, Flatten
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import learning_curve
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
X_train_1 = pd.read_csv('dataset storey 1.csv',index_col=None).iloc[:,:-3]
y_train_1 = pd.read_csv('dataset storey 1.csv',index_col=None).iloc[:,[-3,-2]]
X_test_1 = pd.read_csv('datatest storey 1.csv',index_col=None).iloc[:,:-3]
y_test_1 = pd.read_csv('datatest storey 1.csv',index_col=None).iloc[:,[-3,-2]]
print(X_train_1)
print(X_test_1)

In [ ]:
X_train_2 = pd.read_csv('dataset storey 2.csv',index_col=None).iloc[:,:-3]
y_train_2 = pd.read_csv('dataset storey 2.csv',index_col=None).iloc[:,[-3,-2]]
X_test_2 = pd.read_csv('datatest storey 2.csv',index_col=None).iloc[:,:-3]
y_test_2 = pd.read_csv('datatest storey 2.csv',index_col=None).iloc[:,[-3,-2]]
print(X_train_2)
print(X_test_2)

In [ ]:
X_train_full = pd.read_csv('dataset multi storey.csv',index_col=None).iloc[:,:-3]
y_train_full = pd.read_csv('dataset multi storey.csv',index_col=None).iloc[:,[-1]]
X_test_full = pd.read_csv('datatest multi storey.csv',index_col=None).iloc[:,:-3]
y_test_full = pd.read_csv('datatest multi storey.csv',index_col=None).iloc[:,[-1]]
y_test_full2 = pd.read_csv('datatest multi storey.csv',index_col=None).iloc[:,[-3,-2]]
print(X_train_full)
print(X_test_full)

In [ ]:
y_test_full

In [ ]:
def custom_mse(y_true, y_pred):
    err=y_true - y_pred
    err2= np.square(err)
    err3 =np.sum(err2,axis=1)
    err4 =np.sqrt(err3)
    loss =np.sum(err4)/err4.shape[0]
    
    return loss
def stdev(mse,y_true,y_pred):
    err= y_true - y_pred
    err2= np.square(err)
    err3 =np.sum(err2,axis=1)
    err4 =np.sqrt(err3)
    err5 =mse-err4
    err6 =np.square(err5)
    dev = np.sqrt(np.sum(err6)/err4.shape[0])
    
    return dev

In [ ]:
model_rf1 = RandomForestRegressor(random_state=42,criterion='mse')
model_rf2 = RandomForestRegressor(random_state=42,criterion='mse')
model_rf3 = RandomForestClassifier(random_state=42,criterion='entropy')

param_model_rf = {'n_estimators': [10,20,50,100,200],
    'max_depth' : [4,5,8],
    'min_samples_leaf': [1, 2, 4],
    'min_samples_split': [2, 5, 10],
    'bootstrap' : [True, False]}

cv_rf1 = RandomizedSearchCV(estimator=model_rf1, param_distributions=param_model_rf, cv= 5)
cv_rf2 = RandomizedSearchCV(estimator=model_rf2, param_distributions=param_model_rf, cv= 5)
cv_rf3 = RandomizedSearchCV(estimator=model_rf3, param_distributions=param_model_rf, cv= 5)

model_knn1 = neighbors.KNeighborsRegressor()
model_knn2 = neighbors.KNeighborsRegressor()
model_knn3 = neighbors.KNeighborsClassifier()

param_model_knn = {'n_neighbors' :[1,2,5,10],
                   'weights' : ['uniform', 'distance']}

cv_knn1 = RandomizedSearchCV(estimator=model_knn1, param_distributions=param_model_knn, cv= 5)
cv_knn2 = RandomizedSearchCV(estimator=model_knn2, param_distributions=param_model_knn, cv= 5)
cv_knn3 = RandomizedSearchCV(estimator=model_knn3, param_distributions=param_model_knn, cv= 5)

cv_rf1.fit(X_train_1,y_train_1)
cv_knn1.fit(X_train_1,y_train_1)

cv_rf2.fit(X_train_2,y_train_2)
cv_knn2.fit(X_train_2,y_train_2)

cv_rf3.fit(X_train_full,y_train_full)
cv_knn3.fit(X_train_full,y_train_full)

In [ ]:
print(cv_rf1.best_params_)
print(cv_knn1.best_params_)

print(cv_rf2.best_params_)
print(cv_knn2.best_params_)

print(cv_rf3.best_params_)
print(cv_knn3.best_params_)

In [ ]:
best_rf1 = cv_rf1.best_estimator_
best_knn1 = cv_knn1.best_estimator_

best_rf2= cv_rf2.best_estimator_
best_knn2= cv_knn2.best_estimator_

best_rf3 = cv_rf3.best_estimator_
best_knn3= cv_knn3.best_estimator_

In [ ]:
pred1_lantai = best_rf3.predict(X_test_full)
pred2_lantai = best_knn3.predict(X_test_full)

print('Classification report for Random Forest')
print(classification_report(y_test_full, pred1_lantai))

print('Classification report for kNN')
print(classification_report(y_test_full, pred2_lantai))

In [ ]:
# y_test_full.iloc[i][0]

In [ ]:
mse = 0
tabel =pd.DataFrame(columns=['floor_true','floor_pred','error_floor','x_true','y_true','x_pred','y_pred','error_loc'])
for i in range(X_test_full.shape[0]):
    pred1_lantai = best_rf3.predict(X_test_full.iloc[i].to_numpy().reshape(1, -1))
    print('Lantai {}.'.format(str(pred1_lantai[0])))

    
    if pred1_lantai == 1:
        
        pred_loc1 = best_rf1.predict(X_test_full.iloc[i].to_numpy().reshape(1, -1))
        
        label1 = y_test_full2.iloc[i].to_numpy().reshape(1, -1)
        
        fig = plt.figure(figsize=(10,5))
        fig.suptitle('Localization using random forest in {x} m , {y} m.'.format(x=label1[0][0], y=label1[0][1]), fontsize=12)
        ax = fig.gca()
        ax.set(xlim=(-1,10), ylim=(-1, 10))
        ax.set_ylabel('meter')
        ax.set_xlabel('meter')
        plt.yticks(np.arange(-1, 10, step=1))
        plt.xticks(np.arange(-1, 10, step=1))
        x_1 = [0, 7]
        y_1 = [0, 0]
        x_2 = [7, 7]
        y_2 = [0, 8]
        x_3 = [7, 0]
        y_3 = [8, 8]
        x_4 = [0, 0]
        y_4 = [8, 0]
        plt.plot(x_1, y_1,color='green',label='Area of interest')
        plt.plot(x_2, y_2,color='green')
        plt.plot(x_3, y_3,color='green')
        plt.plot(x_4, y_4,color='green')
        plt.scatter(pred_loc1[0][0],pred_loc1[0][1],label='prediction positions')
        plt.scatter(label1[0][0],label1[0][1],label='actual position')
        plt.grid()
        ax.legend()
        plt.show()

        mse = mse + custom_mse(label1,pred_loc1)
        print('Nilai MAE untuk RF: {:0.2f} meter.'.format(custom_mse(label1,pred_loc1)))
        print(pred_loc1[0][0])
        tabel = tabel.append({'lt_true': y_test_full.iloc[i][0], 'lt_pred': str(pred1_lantai[0]), 
                              'x_true': label1[0][0],'x_pred':round(pred_loc1[0][0],2),
                              'y_true': label1[0][1],'y_pred':round(pred_loc1[0][1],2),
                              'error_lt':y_test_full.iloc[i][0]-float(pred1_lantai[0]),
                              'error_loc':round(custom_mse(label1,pred_loc1),2)}, ignore_index=True)
        print('')
        
    if pred1_lantai == 2:
        pred_loc2 = best_rf2.predict(X_test_full.iloc[i].to_numpy().reshape(1, -1))
        
        label2 = y_test_full2.iloc[i].to_numpy().reshape(1, -1)
        
        fig = plt.figure(figsize=(10,5))
        fig.suptitle('Localization using random forest in {x} m , {y} m.'.format(x=label2[0][0], y=label2[0][1]), fontsize=12)
        ax = fig.gca()
        ax.set(xlim=(-1,10), ylim=(-1, 10))
        ax.set_ylabel('meter')
        ax.set_xlabel('meter')
        plt.yticks(np.arange(-1, 10, step=1))
        plt.xticks(np.arange(-1, 10, step=1))
        x_1 = [0, 8]
        y_1 = [0, 0]
        x_2 = [8, 8]
        y_2 = [0, 9]
        x_3 = [8, 0]
        y_3 = [9, 9]
        x_4 = [0, 0]
        y_4 = [9, 0]
        plt.plot(x_1, y_1,color='green',label='Area of interest')
        plt.plot(x_2, y_2,color='green')
        plt.plot(x_3, y_3,color='green')
        plt.plot(x_4, y_4,color='green')
        plt.scatter(pred_loc2[0][0],pred_loc2[0][1],label='prediction positions')
        plt.scatter(label2[0][0],label2[0][1],label='actual position')
        plt.grid()
        ax.legend()
        plt.show()

        mse = mse + custom_mse(label2,pred_loc2)
        print('Nilai MAE untuk RF: {:0.2f} meter.'.format(custom_mse(label2,pred_loc2)))
        tabel = tabel.append({'lt_true': y_test_full.iloc[i][0], 'lt_pred': str(pred1_lantai[0]), 
                              'x_true': label2[0][0],'x_pred':round(pred_loc2[0][0],2),
                              'y_true': label2[0][1],'y_pred':round(pred_loc2[0][1],2),
                              'error_lt':float(y_test_full.iloc[i][0])-float(pred1_lantai[0]),
                              'error_loc':round(custom_mse(label2,pred_loc2),2)}, ignore_index=True)
        print('')

In [ ]:
print(mse/260)

In [22]:
tabel

     lt_true lt_pred  error_lt  x_true  y_true  x_pred  y_pred  error_loc
0        1.0     1.0       0.0     1.0    1.57    1.00    1.57       0.00
1        1.0     1.0       0.0     1.0    1.57    1.60    2.14       0.83
2        1.0     1.0       0.0     1.0    1.57    1.00    1.57       0.00
3        1.0     1.0       0.0     1.0    1.57    1.00    1.57       0.00
4        1.0     1.0       0.0     1.0    1.57    1.00    1.57       0.00
..       ...     ...       ...     ...     ...     ...     ...        ...
255      2.0     2.0       0.0     6.5    8.25    6.18    8.25       0.32
256      2.0     2.0       0.0     6.5    8.25    6.18    8.25       0.32
257      2.0     2.0       0.0     6.5    8.25    5.97    8.18       0.53
258      2.0     2.0       0.0     6.5    8.25    6.19    8.11       0.34
259      2.0     2.0       0.0     6.5    8.25    6.18    8.25       0.32

[260 rows x 8 columns]

In [26]:
tabel1=tabel.loc[(tabel.iloc[:,1]==str(1.0))]
tabel2=tabel.loc[(tabel.iloc[:,1]==str(2.0))]

In [27]:
tabel2

     lt_true lt_pred  error_lt  x_true  y_true  x_pred  y_pred  error_loc
100      2.0     2.0       0.0     1.0    1.00    2.09    1.96       1.45
101      2.0     2.0       0.0     1.0    1.00    2.00    1.70       1.22
102      2.0     2.0       0.0     1.0    1.00    1.89    1.69       1.13
103      2.0     2.0       0.0     1.0    1.00    2.00    1.70       1.22
104      2.0     2.0       0.0     1.0    1.00    1.86    2.17       1.45
..       ...     ...       ...     ...     ...     ...     ...        ...
255      2.0     2.0       0.0     6.5    8.25    6.18    8.25       0.32
256      2.0     2.0       0.0     6.5    8.25    6.18    8.25       0.32
257      2.0     2.0       0.0     6.5    8.25    5.97    8.18       0.53
258      2.0     2.0       0.0     6.5    8.25    6.19    8.11       0.34
259      2.0     2.0       0.0     6.5    8.25    6.18    8.25       0.32

[160 rows x 8 columns]

In [31]:
tabel1.groupby(["x_true","y_true"]).mean()

               lt_true  error_lt  x_pred  y_pred  error_loc
x_true y_true
1.0    1.57        1.0       0.0   1.120   1.684      0.166
       3.47        1.0       0.0   3.338   2.616      2.496
       5.37        1.0       0.0   1.216   5.648      0.352
       7.27        1.0       0.0   1.070   7.248      0.074
2.2    1.57        1.0       0.0   2.248   1.618      0.068
       3.47        1.0       0.0   2.376   3.398      0.280
       5.37        1.0       0.0   2.380   5.228      0.230
       7.27        1.0       0.0   2.718   6.716      0.858
3.4    1.57        1.0       0.0   3.648   2.252      0.730
       3.47        1.0       0.0   3.376   3.378      0.234
       5.37        1.0       0.0   3.564   5.542      0.248
       7.27        1.0       0.0   3.488   7.254      0.100
4.6    1.57        1.0       0.0   4.600   1.972      0.460
       3.47        1.0       0.0   4.178   3.732      0.530
       5.37        1.0       0.0   4.560   5.362      0.048
       7.27        1.0       0.0   4.546   7.146      0.136
5.8    1.57        1.0       0.0   3.338   2.616      2.684
       3.47        1.0       0.0   5.614   3.380      0.234
       5.37        1.0       0.0   5.596   5.506      0.250
       7.27        1.0       0.0   5.430   6.524      0.878

In [36]:
print("The average error on data at 1st floor : ", tabel1["error_loc"].mean())

The average error on data at 1st floor :  0.5528

In [33]:
tabel2.groupby(["x_true","y_true"]).mean()

               lt_true  error_lt  x_pred  y_pred  error_loc
x_true y_true
1.0    1.00        2.0       0.0   1.968   1.844      1.294
       2.45        2.0       0.0   1.972   2.488      0.984
       3.90        2.0       0.0   1.556   3.986      0.726
       5.35        2.0       0.0   1.662   5.524      0.732
       6.80        2.0       0.0   3.346   5.578      2.658
       8.25        2.0       0.0   1.092   8.250      0.092
2.1    1.00        2.0       0.0   2.166   2.688      1.736
       2.45        2.0       0.0   1.906   2.544      0.436
       3.90        2.0       0.0   2.438   3.274      0.788
       5.35        2.0       0.0   1.904   4.838      0.566
       6.80        2.0       0.0   2.540   6.336      0.644
       8.25        2.0       0.0   2.372   8.226      0.274
3.2    1.00        2.0       0.0   3.764   1.308      0.662
       2.45        2.0       0.0   3.760   2.602      0.662
       5.35        2.0       0.0   2.828   5.950      0.710
       6.80        2.0       0.0   3.234   6.680      0.770
       8.25        2.0       0.0   2.786   7.912      0.556
4.3    1.00        2.0       0.0   3.546   1.644      1.054
       2.45        2.0       0.0   4.426   2.112      0.842
       8.25        2.0       0.0   3.992   7.172      1.130
5.4    1.00        2.0       0.0   5.386   1.622      0.658
       2.45        2.0       0.0   4.094   2.332      1.360
       3.90        2.0       0.0   5.224   3.370      0.662
       5.35        2.0       0.0   5.194   5.884      0.568
       6.80        2.0       0.0   5.236   6.080      0.752
       8.25        2.0       0.0   5.262   8.216      0.752
6.5    1.00        2.0       0.0   5.386   1.622      1.320
       2.45        2.0       0.0   5.930   4.002      1.652
       3.90        2.0       0.0   5.590   4.076      0.980
       5.35        2.0       0.0   6.194   4.842      0.620
       6.80        2.0       0.0   6.052   6.470      0.560
       8.25        2.0       0.0   6.140   8.208      0.366

In [37]:
print("The average error on data at 2nd floor : ",tabel2["error_loc"].mean())

The average error on data at 2nd floor :  0.8614374999999999